### ISSUE TITLE
baseurl -> https/http 동시지원

### ISSUE THREAD

**Issue by if1live** [5minlab/5minlab.github.io#2]
적당히 잘 우회해야되는데
http로 접속시 https로 리다이렉트 하는것도 넣어야하는데

**Comment by goyusia** [comment]
https://github.com/5minlab/5minlab.github.io/commit/d9e7b19a566087956d623f8cb46f30fef5cbf2d8
리다이렉트 없이 일단 꺠지진 않도록 만듬
